---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Task Management
  labels:
    app: Task Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Task Management
  template:
    metadata:
      labels:
        app: Task Management
    spec:
      containers:
        - name: Task Management
          image: username/Task Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: User Authentication
  labels:
    app: User Authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: User Authentication
  template:
    metadata:
      labels:
        app: User Authentication
    spec:
      containers:
        - name: User Authentication
          image: username/User Authentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Task Management
  labels:
    app: Task Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Task Management


---


apiVersion: v1
kind: Service
metadata:
  name: User Authentication
  labels:
    app: User Authentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User Authentication

