server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Task Management
          uri: http://localhost:8082
          predicates:
            - Path=/tasks/**, 
        - id: User Authentication
          uri: http://localhost:8083
          predicates:
            - Path=/authentications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Task Management
          uri: http://taskManagement:8080
          predicates:
            - Path=/tasks/**, 
        - id: User Authentication
          uri: http://userAuthentication:8080
          predicates:
            - Path=/authentications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
