apiVersion: v1
kind: Service
metadata:
  name: User Authentication
  labels:
    app: User Authentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User Authentication